### ISSUE TITLE
Bug: Baby pets have adult skins

### ISSUE THREAD

**Issue by CJBlakey** [Jakllp/MyPet#15]
The command '/petadmin create (name) bee baby' should create a baby bee as a pet, it currently creates an adult pet.
The name argument and from what I can tell the pcst arguments work fine

Edit: The mob that is spawned as a result of releasing the pet is in fact a baby, leading me to believe that the pets just have the incorrect skin?

**Comment by CJBlakey** [comment]
Bizarre update - if you then /petrelease and click the pet name to confirm the release a baby animal takes it's place. It seem that it is in fact spawning a baby animal, but with the skin of an adult one? make of that what you will? apologies for the lack of formatting in this issue

**Comment by CJBlakey** [comment]
have confirmed this issue with both bees and chickens, cant currently think of any other pets that allow baby states

**Comment by Jakllp** [comment]
Fixed in https://github.com/Jakllp/MyPet/commit/56517a03572391493e45ae4c1d4c0d5e98b98786
