### ISSUE TITLE
UseMojangMappings - This will take a bit

### ISSUE THREAD

**Issue by Ghost-chu** [Jakllp/MyPet#17]
It's really hard to read the whole plugin code.
Use mapping would be better, at least no longer need to find what `K` means. It really painful.

https://www.spigotmc.org/threads/spigot-bungeecord-1-17-1-17-1.510208/#post-4184317

**Comment by Jakllp** [comment]
Making good progress - No timeline tho. Don't wanna stress myself out

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/1dd9bd1a2b1e3057fbcfb106a50ba60bfa0806b4

Will merge to master once https://github.com/Jakllp/MyPet/pull/25 has been merged and also remapped

**Comment by Jakllp** [comment]
Merged to master https://github.com/Jakllp/MyPet/commit/c5cb6ac643e5e87dbde83cbed3ac0a1c46b08817
