### ISSUE TITLE
[Suggestion] AxolotlAi

### ISSUE THREAD

**Issue by CJBlakey** [Jakllp/MyPet#33]
If we're not totally burnt out and hating Minecraft once a stable 1.17.1 conversion is achieved, we may be able to extend Axolotl functionality to include behaviours such as:
Play dead
Idle roaming 
Fight activity (suspect this allows the entity to attack nearest of a given list of targets)
`c	net/minecraft/world/entity/animal/axolotl/AxolotlAi	net/minecraft/world/entity/animal/axolotl/AxolotlAi
	m	(Lnet/minecraft/world/entity/LivingEntity;)Z	canSetWalkTargetFromLookTarget	a
	m	(Lnet/minecraft/world/entity/animal/axolotl/Axolotl;)Ljava/util/Optional;	findNearestValidAttackTarget	b
	m	(Lnet/minecraft/world/entity/LivingEntity;)F	getSpeedModifier	d
	m	(Lnet/minecraft/world/entity/LivingEntity;)F	getSpeedModifierChasing	b
	m	(Lnet/minecraft/world/entity/LivingEntity;)F	getSpeedModifierFollowingAdult	c
	m	()Lnet/minecraft/world/item/crafting/Ingredient;	getTemptations	a
	m	(Lnet/minecraft/world/entity/ai/Brain;)V	initCoreActivity	d
	m	(Lnet/minecraft/world/entity/ai/Brain;)V	initFightActivity	c
	m	(Lnet/minecraft/world/entity/ai/Brain;)V	initIdleActivity	e
	m	(Lnet/minecraft/world/entity/ai/Brain;)V	initPlayDeadActivity	b
	m	(Lnet/minecraft/world/entity/animal/axolotl/Axolotl;)Z	isBreeding	c
	m	(Lnet/minecraft/world/entity/ai/Brain;)Lnet/minecraft/world/entity/ai/Brain;	makeBrain	a
	m	(Lnet/minecraft/world/entity/animal/axolotl/Axolotl;)V	updateActivity	a
	f	Lnet/minecraft/util/valueproviders/UniformInt;	ADULT_FOLLOW_RANGE	a
	f	F	SPEED_MULTIPLIER_ON_LAND	c
	f	F	SPEED_MULTIPLIER_WHEN_CHASING_IN_WATER	e
	f	F	SPEED_MULTIPLIER_WHEN_FOLLOWING_ADULT_IN_WATER	f
	f	F	SPEED_MULTIPLIER_WHEN_IDLING_IN_WATER	d
	f	F	SPEED_MULTIPLIER_WHEN_MAKING_LOVE	b`

**Comment by Jakllp** [comment]
Play dead is now in with `3.12-SNAPSHOT-B1686`
And it was done in https://github.com/MyPetORG/MyPet/commit/734ca3da72dcc53baa95e6f67eec41a35d759013 and https://github.com/MyPetORG/MyPet/commit/582c8155fcea8edfcaf01e999b7425e7049b2094

**Comment by Jakllp** [comment]
Idle Roaming and stuff would be general things to be potentially added at some point which is why I'm closing this issue now
