### ISSUE TITLE
Problems connecting SQL-Database

### ISSUE THREAD

**Issue by MARODEUR** [Jakllp/MyPet#46]
Hi there,

tried out the latest 1.17.1 dev-build (no. 8) with latest papermc 1.17.1 Version.
For whatever Reason the connection to the SQL Server is now failing. This was not the case with mypet and paper under 1.16.. 
MyPet is the only plugin having this problem, all others plugin can connect without a problem. Iam using a mariadb, everythings up to date. 

Error in Console:

```
[15:36:47] [Server thread/INFO]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [mConnect to MySQL database...[m
[15:36:48] [Server thread/WARN]: [de.Keyle.MyPet.MyPetPlugin] [[0;32;22mMyPet[m] [m[0;31;1mMySQL connection failed![m
[15:36:48] [Server thread/WARN]: RepositoryInitException{exception=com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[15:36:48] [Server thread/WARN]: 
[15:36:48] [Server thread/WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.}
[15:36:48] [Server thread/WARN]: 	at MyPet.jar//de.Keyle.MyPet.repository.types.MySqlRepository.init(MySqlRepository.java:97)
[15:36:48] [Server thread/WARN]: 	at MyPet.jar//de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:341)
[15:36:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:36:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:36:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:36:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
[15:36:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
[15:36:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:654)
[15:36:48] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[15:36:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1141)
[15:36:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:36:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

Config:

  Repository:
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 20
    MySQL:
      Database: DBNAME
      TablePrefix: mypet_
      Host: XXX.XXX.XXX.122
      Password: CENSORED
      User: DBUSER
      Port: 3306
      MaxConnections: 8
      CharacterEncoding: utf8

I dont know whats the issue here, any ideas? Problem with SQL Connector?

**Comment by Jakllp** [comment]
Note: Should be the same in dev9 as no SQL-Code has been touched

**Comment by Jakllp** [comment]
I'm guessing you used the same config under 1.16?

**Comment by Jakllp** [comment]
This issue indicates problems with the config/the database server (i tried a DB-Connection myself and it worked)

## Explanation
I'm gonna quote something I found on stackoverflow (our Lord and Savior)
If you get a SQLException: Connection refused or Connection timed out or a MySQL specific CommunicationsException:
Communications link failure, then it means that the DB isn't reachable at all. This can have one or more of the following causes:

1. IP address or hostname in JDBC URL is wrong.
1. Hostname in JDBC URL is not recognized by local DNS server.
1. Port number is missing or wrong in JDBC URL.
1. DB server is down.
1. DB server doesn't accept TCP/IP connections.
1. DB server has run out of connections.
1.  Something in between Java and DB is blocking connections, e.g. a firewall or proxy.
([Source](https://stackoverflow.com/questions/2983248/com-mysql-jdbc-exceptions-jdbc4-communicationsexception-communications-link-fai))

## How to resolve this:
I would ask you to check your config and increase the "MaxConnections" (default is 32)

**Comment by Jakllp** [comment]
(closed on accident)

**Comment by MARODEUR** [comment]
Yeah, no config changes. No Problem in connection with other plugins.
I tried it again from another server with same configs, same Problem. 
I even created a new, empty database and used that in the config, but that changed nothing.

_IP address or hostname in JDBC URL is wrong._
-> No, its definitely correct.

_Hostname in JDBC URL is not recognized by local DNS server._
-> I tried it by IP and Hostname, both connections failed.

_Port number is missing or wrong in JDBC URL._
-> Port ist correct.

_DB server is down._
-> No, 3 other Servers can connect it without problems. Other plugins on my 1.17 Testserver can connect it as well - only MyPet    has this issue.

_DB server doesn't accept TCP/IP connections._
-> It does

_DB server has run out of connections._
-> Nope, checked this already. 

_Something in between Java and DB is blocking connections, e.g. a firewall or proxy_
-> Possible, but i would say no to this, cause other plugins on the same running server dont have this Problem.

==================

Well, iam not a developer so i tried a little around. New database, hostname instead of IP adress, checked all database permissions, firewall rules etc - connectivity is there. All other plugins on this specific 1.17.1 testserver can connect the mariadb-server (same DB-server, same port, same user & pw). Some of them are using a deprecated sqlconnector as it seems, but still connect:

> [17:19:38 INFO]: [Jobs] Enabling Jobs v5.0.0.6
[17:19:38 ERROR]: [[STDERR] ] com.mysql.jdbc.Driver Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.
 The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

So based on your statement that nothing has changed in the SQL Code i searched further around:
With older 1.16.5 PaperMC Builds and the latest official MyPet 1.16.5 dev-build the error does not happen. 
But when i use PaperMC Version build#588 and newer, the error in MyPet appears. 
Changelog paper build #588: Bump mysql-connector-java to 8.0.23

And thats the point where it breaks on all my servers. I dont know if it is a missing dependency /repository that i need to install on my servers (Debian) for MyPet being able to connect the database, but i dont get why only MyPet has this problem..

Thanks for any help and sorry for the long post - spend a lot of time in that^^

**Comment by Jakllp** [comment]
Damn that's what I call research!
Nice find with the mysql-connector version change... Weird.

I just updated my 1.17.1 PaperMC (was around 20 builds behind) and it still didn't break...
I'm gonna look for some more clues

**Comment by Jakllp** [comment]
As I can't just send a jar here -> I've attached a zip with two slightly different jars. Could you try them and report back?

[MyPet-SQL.zip](https://github.com/Jakllp/MyPet/files/7077898/MyPet-SQL.zip)

**Comment by MARODEUR** [comment]
The issue appears in 1.16.5 already. In my case:
Using latest MyPet 1.16.5 Dev Build (#1642) with Paper Build 587 => Works.
Using latest MyPet 1.16.5 Dev Build (#1642) with Paper Build 588 => SQL Error.
Using latest MyPet Dev-Build from you (d8) with latest Paper 1.17.1 => Still SQL Error.

Something must have been changed there in spigot/paper that breaks the mypet sql connection on my servers.. but just for MyPet. Thats why i thought of a missing repository that mypet needs? But my servers are absolutely basic, default debian installation with openjdk16-hotspot installed.

====

I tried both your SQL Versions and configured the plugin Jobs with the exact same DB-Config (except the table prefix, ofc ;) and tried Hostname and IP, deactivated firewall for the test.
MyPet MySQL Config used:

```
  Repository:
    Type: MySQL
    ConvertFrom: ''
    LoadDelay: 40
    MySQL:
      Database: mypet
      TablePrefix: mypet_
      Host: XXX.XXX.XXX.122
      Password: XXcrazyPWwithlotsOfSonderzeichenundsoXX
      User: XXXXX
      Port: 3306
      MaxConnections: 32
      CharacterEncoding: utf8
```
Result is sadly still the same, while Jobs can connect without any Problems. Even used the SQL-Admin for excluding a permission Problem.

Here the full Server Startup-Logs:

MyPet SQL-Version1:
[https://pastebin.com/2kXnsKce](url)

MyPet SQL-Version2:
[https://pastebin.com/HHD0kWnz](url)

**Comment by Jakllp** [comment]
So it wasn't as easy as just updating the dependency. Sad

**Comment by Jakllp** [comment]
I just installed MariaDB myself and even tested the old versions and it worked...
Potentially java not being up to date/being too up to date (the latter wouldn't make sense bc both SQL-Versions didn't work)

The only difference between our configs (except for the obvious stuff) is the LoadDelay - I've got 20, you've got 40
That would be the only quick thing you could try.
After that it's a lot of digging I guess

**Comment by MARODEUR** [comment]
Have you tried it with the old 1.16.5 dev builds with Paper Build 587 and then upgrading to 588?
Could it be an issue with SSL? Perhaps MyPet is trying to establish the connection with SSL? (which i have enabled on the MariaDB Server, but i dont use it - and mypet does not have an ssl option for the DB connection)

My servers are all running on Debian 10.10 and have latest OpenJDK16 Hotspot installed. My MariaDB Server is on another server than the testserver, but that shouldn't be a problem. As you can see in the logs, other plugins can connect without a problem. What Java Version are you using (if you are on linux)? Maybe something is missing on my servers which MyPet uses?

I tried a little around with the LoadDelay, i dont know for what exactly this option is. Thought this might be a timeout interval and by increasing this, i could maybe exclude a slow response from my DB as the cause. Its not working with 20 tho.

Die "LotsOfSonderzeichen" kommen dabei rum, wenn der Kopf vom ganzen rumprobieren langsam aussteigt :P

**Comment by CJBlakey** [comment]
Going to try this on my server, currently running mariadb on ubuntu 20.04, last I checked the dev builds were reading my existing mypet db's fine

**Comment by Sponge1996** [comment]
Do you use umlauts or special characters in your login data?

**Comment by MARODEUR** [comment]
> Do you use umlauts or special characters in your login data?

Yes I do, might this be a problem?

**Comment by Jakllp** [comment]
Would be quite interesting as it doesn't seem to impact other plugins...

**Comment by Sponge1996** [comment]
could you please create a test user who has rights to the table structure of Mypet and uses a password without umlauts or special characters?
If this can connect without problems, we have largely narrowed down the error

**Comment by MARODEUR** [comment]
> 
> 
> could you please create a test user who has rights to the table structure of Mypet and uses a password without umlauts or special characters?
> If this can connect without problems, we have largely narrowed down the error

Done, sadly that was not the problem. Still the same error

**Comment by MARODEUR** [comment]
Good news, i finally got it to work.

When i setup my maria-db i prepared it for using SSL-communication later in the future, since i have 3 Servers that connects remote.
So i setup the SSL options and SSL Certs in 
/etc/mysql/my.cnf
/etc/mysql/mariadb.conf.d/mysql-clients.cnf
/etc/mysql/mariadb.conf.d/server.cnf
but i did NOT set the usage of SSL Encryption to REQUIRED (in mariadb-config and for the db-user). This worked well, especially with plugins that do not have an SSL option in their configs. So i let them connect without SSL (all traffic goes through an internal network). After the update of the jdbc with paper build 588 (if i understood that correctly) mypet seems to have trouble connecting to it, cause the DB has SSL option enabled.

Long story short: i completely disabled all SSL configurations on my MariaDB-Server in above mentioned configs, reloaded the MariaDB and voila - mypet can connect again from every version and every server.

My understanding is, that the SQL functions of mypet somehow tried to establish an SSL connection with paper >build588 to my DB, which was not setup correctly (since i did not use it) and it failed. Even though there is no specific option in mypet for using ssl instead of no encryption. This behaviour appeared with the jdbc change from paper in 1.16.5 build588. Before it just worked.
Maybe iam totally wrong, iam not a developer and iam not very deep into jdbc connections, but this is my theory what happens here. A possible way would be maybe an option in mypet for enable or disable SSL usage in the DB-Connection, like many other plugins can do it now. 

All in all it works for me now, and i just want to thank everyone who helped me here. Especially @Jakllp for his effort keeping this awesome plugin alive :)

**Comment by Jakllp** [comment]
![image](https://user-images.githubusercontent.com/57708725/131583351-2b7c19b3-5245-4bbd-a684-e97979d4ed1a.png)

Just found this on the MyPet-Discord
