### ISSUE TITLE
Every pet looks like a pig.

### ISSUE THREAD

**Issue by UmNyom** [Jakllp/MyPet#49]
Thank you for always caring and working hard to develop.

Many errors have been fixed before, and there are no errors when the server is running.

The compatibility of multiple commands and databases is normal.

If you summon a pet, it's working fine.

Getting on and off the pet also works fine.

But all the pets are pigs.

I can summon the other pets, but they're all pigs.

There is no sound of a pig.

Only the appearance is pig

- 

I'm glad that we're gradually approaching development completion.

Please solve this problem.

-

[2021-09-01_10 38 22]
(https://user-images.githubusercontent.com/81360008/131599037-23a4cc1e-1b9c-4963-8db6-5e227133b2c3.png)

**Comment by UmNyom** [comment]
My Plugin

Let me know if you need an Edon plug-in.

(https://user-images.githubusercontent.com/81360008/131601903-94c9b981-63e3-4046-8fbd-65af3c82e352.PNG)

**Comment by Jakllp** [comment]
Try https://github.com/Jakllp/MyPet/releases it's fixed in there ^^
