### ISSUE TITLE
Leash sometimes won't work

### ISSUE THREAD

**Issue by MatessCZ** [Jakllp/MyPet#54]
Hi, I experience a problem with leashing pets on my server. When I make a new, clean intall of plugin, it works with default and even with custom leash item. When I wait ex. 1 hour, not editing ANY config files, it suddenly stops working. Yeah, I can still make pets via command, but its better when players have to do it by themselves.

Tried deleting all files of plugin MyPet - result as I wrote above (working for like 1 hour)

Removing some other plugins that could cause problems, but it's same everytime.

Tried updating paperspigot from 1.17.1 - 112 to 1.17.1 - 249 -> no difference

Tried switching from paperspigot to latest "regular" spigot -> still nothing

In logs/console aren't any errors or bugs from myPet

MyPet version: 3.12-RC3 (latest)
Uploading ticket.zip
[ticket.zip](https://github.com/Jakllp/MyPet/files/7111322/ticket.zip)

Thank you for what you are doing, its great!
Looking forward to hear from you :)

**Comment by Jakllp** [comment]
Just looked at the log - you did /psa to send away the cow
You need to store the pet (/petstore) - This "unequips" the pet properly and allows you to capture another one. Might that have been the problem?

**Comment by MatessCZ** [comment]
Yeah, it looks like it's working. 
_That /pc that I typed was /petcall._
Thank you for solving, didn't knew I had to store that pet

**Comment by Jakllp** [comment]
No problem - Glad we could solve it ^^
