### ISSUE TITLE
Will this be merged into the original?

### ISSUE THREAD

**Issue by kn-km** [Jakllp/MyPet#57]
# Question about MyPet
Hi, guy

I want to ask will this be merged into the original? Or it will be an independent repo?
_Please describe what is on your mind. If possible also provide a context and your end goals._

* [x] I have asked for help on other places like Discord ord the discussion on spigotmc.org

**Comment by Jakllp** [comment]
Yes, and that should be faaaiirly soon.
[RC3](https://github.com/Jakllp/MyPet/releases/tag/3.12-RC3) is pretty much stable but still has some bugs. Gonna squash those, wait some more for potential bugs to emerge.

After that I'm gonna prepare the merge.
