### ISSUE TITLE
Bug: Piglins can't be babies

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#58]
Piglin-Pets with the baby-tag are normal Piglins
(also in 1.16)

Might be the AGE_WATCHER (should potentially be BABY_WATCHER but was AGE_WATCHER for PigZombies?)
Or something else

**Comment by Jakllp** [comment]
Done in https://github.com/Jakllp/MyPet/commit/5b93860dcc229ce45452687ca40999eb8fee7ea3

**Comment by Ophagan** [comment]
Hello, how could I download the .jar for version 1.17, the truth is, I don't have the slightest idea of ​​programming or anything, please help me: D

**Comment by Jakllp** [comment]
So this right now is 1.17.1

If you want the latest jar is here:
https://github.com/Jakllp/MyPet/releases/tag/3.12-RC4

It doesn't have the piglin fix in it yet but yeah

For the future:
I think this will be merged into the main mypet repository.
That means that you can download it just like you used to download 1.16 jars etc

**Comment by Jakllp** [comment]
Alrighty - As for the Piglins AND where to download the jar:
Look no further than https://mypet-plugin.de/download - 3.12-SNAPSHOT
