### ISSUE TITLE
Bug: Custom Inventories are empty

### ISSUE THREAD

**Issue by Jakllp** [Jakllp/MyPet#6]
Custom inventories (aka menus) are completely empty (slot listeners are being set up)

The item-stacks SEEM to be created properly - might not -  but they don't show up on the inventory.

There is no console error.

**Comment by Jakllp** [comment]
Possibly fixed soon (Thanks Tragur (their discord name))

**Comment by Sponge1996** [comment]
https://github.com/Jakllp/MyPet/pull/14
