### ISSUE TITLE
Pet despawns and respawns when following ends

### ISSUE THREAD

**Issue by aaronaustin0** [Jakllp/MyPet#77]
# Bug report

* [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Pet keeps despawning after follow sequence.

## To Reproduce

_Steps to reproduce the behavior, please provide code snippets or a repository:_

When moving 7+ blocks away from the pet, it starts to run toward you. Upon reaching you and stopping, it despawns. It then automatically respawns and displays a chat message that it respawned.

## Expected behavior

The pet does not despawn and respawn after coming to a stop after following.

## Actual behaviour

![image](https://user-images.githubusercontent.com/26975565/148310151-a610fa29-51f3-4b38-abf0-a46387252edd.png)

## Additional context

> Please use the `/petadmin ticket` command and attach the generated `ticket.zip` from the MyPet folder to this issue.

[ticket.zip](https://github.com/Jakllp/MyPet/files/7818629/ticket.zip)

**Bukkit/Spigot/Bungee Build/Version:**
Paper 1.18.1-101

**MyPet Build/Version:**
3.12-1.18-dev1

**Error:**
```
PUT ERROR HERE IF NOT LONGER THAN ~10 LINES
```

**Comment by Jakllp** [comment]
This fork isn't the main project which is why the build you downloaded is for 1.18 and not 1.18.1 - which is probably the problem here.
Please update to 3.12-SNAPSHOT over from the official page:
https://mypet-plugin.de/download

If the problem persists after that please check your console for any errors.

**Comment by Jakllp** [comment]
Did it help?

**Comment by aaronaustin0** [comment]
That worked.

Thank you
